server:
  port: 8080

spring:
  profiles:
    active: dev

  datasource:
    name: material_counting
    url: jdbc:mysql://localhost:3306/material_counting?serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.232.31
#    port: 6379
#    jedis: # 连接池
#      pool:
#        max-active: 50
#        min-idle: 20
#    database: 10
#    password:
mybatis-plus:
  mapper-locations: classpath:mapping/*.xml
